"""criar tabelas iniciais

Revision ID: 8d3599902f84
Revises: 
Create Date: 2026-08-14 21:23:34.689485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3599902f84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('setores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('treinamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('norma', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('carga_horaria', sa.Float(), nullable=True),
    sa.Column('validade_meses', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treinamentos_ativo'), 'treinamentos', ['ativo'], unique=False)
    op.create_index(op.f('ix_treinamentos_categoria'), 'treinamentos', ['categoria'], unique=False)
    op.create_index(op.f('ix_treinamentos_nome'), 'treinamentos', ['nome'], unique=False)
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_demissao', sa.Date(), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_funcionarios_ativo'), 'funcionarios', ['ativo'], unique=False)
    op.create_index(op.f('ix_funcionarios_nome'), 'funcionarios', ['nome'], unique=False)
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('treinamento_id', sa.Integer(), nullable=False),
    sa.Column('data_realizacao', sa.Date(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('instrutor', sa.String(length=200), nullable=True),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treinamento_id'], ['treinamentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matriculas_data_realizacao'), 'matriculas', ['data_realizacao'], unique=False)
    op.create_index(op.f('ix_matriculas_data_validade'), 'matriculas', ['data_validade'], unique=False)
    op.create_index(op.f('ix_matriculas_funcionario_id'), 'matriculas', ['funcionario_id'], unique=False)
    op.create_index(op.f('ix_matriculas_treinamento_id'), 'matriculas', ['treinamento_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('arquivo_nome', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificados')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_matriculas_treinamento_id'), table_name='matriculas')
    op.drop_index(op.f('ix_matriculas_funcionario_id'), table_name='matriculas')
    op.drop_index(op.f('ix_matriculas_data_validade'), table_name='matriculas')
    op.drop_index(op.f('ix_matriculas_data_realizacao'), table_name='matriculas')
    op.drop_table('matriculas')
    op.drop_index(op.f('ix_funcionarios_nome'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_ativo'), table_name='funcionarios')
    op.drop_table('funcionarios')
    op.drop_index(op.f('ix_treinamentos_nome'), table_name='treinamentos')
    op.drop_index(op.f('ix_treinamentos_categoria'), table_name='treinamentos')
    op.drop_index(op.f('ix_treinamentos_ativo'), table_name='treinamentos')
    op.drop_table('treinamentos')
    op.drop_table('setores')
    op.drop_table('cargos')
    # ### end Alembic commands ###
