"""criar tabela gestores

Revision ID: 913fd74ebbda
Revises: c3d4e5f60718
Create Date: 2026-08-15 21:06:37.591985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913fd74ebbda'
down_revision: Union[str, None] = 'c3d4e5f60718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.Column('foto_tipo', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gestores_nome'), 'gestores', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gestores_nome'), table_name='gestores')
    op.drop_table('gestores')
    # ### end Alembic commands ###
